# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['0.0.0.0:9090']

  - job_name: 'DummyApp'
    consul_sd_configs:
     - server: 'localhost:8500'
       services: ['web']
       allow_stale: false
       refresh_interval: 15s
       tag: 'Dummy'
       datacenter: 'dc1'

    relabel_configs:
     - source_labels: ['__meta_consul_node']
       regex:         '(.*)'
       target_label:  'instance'
       replacement:   '$1'
